# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94878d69448869a3bdd7ba9cb3288062ca41336af13acd75f34b53e324e0d89707086f978a348c996d2e3e94037cf0a042860f8d7b080c52ceb33a1db0cab752

test:
  secret_key_base: ed5df005e0fecbeaa3eb12cdd7a321fb23025561921fbb7b7dcadd149e4f8e3dc8930e6936b2897b38731bd6c03dde4f9d890df0b0144fb0026630f97c037a60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
